"""add_has_catalog_products_field

Revision ID: 20250106140000_add_has_catalog_products_field
Revises: 20250106130000
Create Date: 2025-01-06 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '20250106140000_add_has_catalog_products_field'
down_revision = '20250106130000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_orders', sa.Column('has_catalog_products', sa.Boolean(), nullable=True))
    op.create_index('ix_ml_orders_has_catalog_products', 'ml_orders', ['has_catalog_products'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ml_orders_has_catalog_products', table_name='ml_orders')
    op.drop_column('ml_orders', 'has_catalog_products')
    # ### end Alembic commands ###
