"""add catalog participants table

Revision ID: 20250104130000
Revises: d47b12a95c94
Create Date: 2025-01-04 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20250104130000'
down_revision = '196099bd573d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('catalog_product_id', sa.String(length=50), nullable=False),
    sa.Column('ml_item_id', sa.String(length=50), nullable=False),
    sa.Column('seller_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('available_quantity', sa.Integer(), nullable=True),
    sa.Column('sold_quantity', sa.Integer(), nullable=True),
    sa.Column('permalink', sa.String(length=500), nullable=True),
    sa.Column('thumbnail', sa.String(length=500), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('listing_type_id', sa.String(length=50), nullable=True),
    sa.Column('official_store_id', sa.String(length=50), nullable=True),
    sa.Column('accepts_mercadopago', sa.Boolean(), nullable=True),
    sa.Column('original_price', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.String(length=50), nullable=True),
    sa.Column('logistic_type', sa.String(length=50), nullable=True),
    sa.Column('buy_box_winner', sa.Boolean(), nullable=True),
    sa.Column('seller_name', sa.String(length=255), nullable=True),
    sa.Column('seller_nickname', sa.String(length=255), nullable=True),
    sa.Column('seller_country', sa.String(length=10), nullable=True),
    sa.Column('seller_city', sa.String(length=100), nullable=True),
    sa.Column('seller_state', sa.String(length=100), nullable=True),
    sa.Column('seller_registration_date', sa.String(length=50), nullable=True),
    sa.Column('seller_experience', sa.String(length=50), nullable=True),
    sa.Column('seller_power_seller', sa.Boolean(), nullable=True),
    sa.Column('seller_power_seller_status', sa.String(length=50), nullable=True),
    sa.Column('seller_reputation_level', sa.String(length=20), nullable=True),
    sa.Column('seller_transactions_total', sa.Integer(), nullable=True),
    sa.Column('seller_ratings_positive', sa.Integer(), nullable=True),
    sa.Column('seller_ratings_negative', sa.Integer(), nullable=True),
    sa.Column('seller_ratings_neutral', sa.Integer(), nullable=True),
    sa.Column('seller_mercadopago_accepted', sa.Boolean(), nullable=True),
    sa.Column('seller_mercadoenvios', sa.String(length=50), nullable=True),
    sa.Column('seller_user_type', sa.String(length=50), nullable=True),
    sa.Column('seller_tags', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_participants_company'), 'catalog_participants', ['company_id'], unique=False)
    op.create_index(op.f('ix_catalog_participants_company_catalog'), 'catalog_participants', ['company_id', 'catalog_product_id'], unique=False)
    op.create_index(op.f('ix_catalog_participants_catalog_product'), 'catalog_participants', ['catalog_product_id'], unique=False)
    op.create_index(op.f('ix_catalog_participants_last_updated'), 'catalog_participants', ['last_updated'], unique=False)
    op.create_index(op.f('ix_catalog_participants_ml_item_id'), 'catalog_participants', ['ml_item_id'], unique=True)
    op.create_index(op.f('ix_catalog_participants_price'), 'catalog_participants', ['price'], unique=False)
    op.create_index(op.f('ix_catalog_participants_seller'), 'catalog_participants', ['seller_id'], unique=False)
    op.create_index(op.f('ix_catalog_participants_status'), 'catalog_participants', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_participants_status'), table_name='catalog_participants')
    op.drop_index(op.f('ix_catalog_participants_seller'), table_name='catalog_participants')
    op.drop_index(op.f('ix_catalog_participants_price'), table_name='catalog_participants')
    op.drop_index(op.f('ix_catalog_participants_ml_item_id'), table_name='catalog_participants')
    op.drop_index(op.f('ix_catalog_participants_last_updated'), table_name='catalog_participants')
    op.drop_index(op.f('ix_catalog_participants_catalog_product'), table_name='catalog_participants')
    op.drop_index(op.f('ix_catalog_participants_company_catalog'), table_name='catalog_participants')
    op.drop_index(op.f('ix_catalog_participants_company'), table_name='catalog_participants')
    op.drop_table('catalog_participants')
    # ### end Alembic commands ###
