"""add_internal_products_table

Revision ID: 20250106130000
Revises: 20250106120000
Create Date: 2025-01-06 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20250106130000'
down_revision = '20250106120000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('base_product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('internal_sku', sa.String(length=100), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('marketing_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('other_costs', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('min_stock', sa.Integer(), nullable=True),
    sa.Column('current_stock', sa.Integer(), nullable=True),
    sa.Column('main_image', sa.String(length=1000), nullable=True),
    sa.Column('additional_images', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['base_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_internal_products_base', 'internal_products', ['base_product_id'], unique=False)
    op.create_index('ix_internal_products_category', 'internal_products', ['category'], unique=False)
    op.create_index('ix_internal_products_company', 'internal_products', ['company_id'], unique=False)
    op.create_index('ix_internal_products_created', 'internal_products', ['created_at'], unique=False)
    op.create_index('ix_internal_products_sku', 'internal_products', ['internal_sku'], unique=False)
    op.create_index('ix_internal_products_status', 'internal_products', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_internal_products_status', table_name='internal_products')
    op.drop_index('ix_internal_products_sku', table_name='internal_products')
    op.drop_index('ix_internal_products_created', table_name='internal_products')
    op.drop_index('ix_internal_products_company', table_name='internal_products')
    op.drop_index('ix_internal_products_category', table_name='internal_products')
    op.drop_index('ix_internal_products_base', table_name='internal_products')
    op.drop_table('internal_products')
    # ### end Alembic commands ###
