"""add_products_table

Revision ID: 20250106120000
Revises: 20250104130000
Create Date: 2025-01-06 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20250106120000'
down_revision = '20250104130000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ml_item_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('thumbnail', sa.String(length=1000), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('cost_price', sa.String(length=20), nullable=True),
    sa.Column('tax_rate', sa.String(length=10), nullable=True),
    sa.Column('marketing_cost', sa.String(length=20), nullable=True),
    sa.Column('other_costs', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_company', 'products', ['company_id'], unique=False)
    op.create_index('ix_products_company_sku', 'products', ['company_id', 'sku'], unique=False)
    op.create_index('ix_products_ml_item', 'products', ['ml_item_id'], unique=False)
    op.create_index('ix_products_sku', 'products', ['sku'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index('ix_products_sku', table_name='products')
    op.drop_index('ix_products_ml_item', table_name='products')
    op.drop_index('ix_products_company_sku', table_name='products')
    op.drop_index('ix_products_company', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###

