"""Initial migration

Revision ID: d47b12a95c94
Revises: 
Create Date: 2025-10-04 20:48:54.045853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd47b12a95c94'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('ml_account_id', sa.Integer(), nullable=False),
    sa.Column('ml_order_id', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('buyer_id', sa.String(length=50), nullable=False),
    sa.Column('buyer_nickname', sa.String(length=255), nullable=True),
    sa.Column('buyer_email', sa.String(length=255), nullable=True),
    sa.Column('buyer_first_name', sa.String(length=255), nullable=True),
    sa.Column('buyer_last_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='orderstatus'), nullable=False),
    sa.Column('status_detail', sa.String(length=100), nullable=True),
    sa.Column('total_amount', sa.Integer(), nullable=True),
    sa.Column('currency_id', sa.String(length=10), nullable=True),
    sa.Column('payment_method_id', sa.String(length=50), nullable=True),
    sa.Column('payment_type_id', sa.String(length=50), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('shipping_cost', sa.Integer(), nullable=True),
    sa.Column('shipping_method', sa.String(length=100), nullable=True),
    sa.Column('shipping_status', sa.String(length=50), nullable=True),
    sa.Column('shipping_address', sa.JSON(), nullable=True),
    sa.Column('feedback', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('order_items', sa.JSON(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['ml_account_id'], ['ml_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ml_orders_buyer_id', 'ml_orders', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_ml_orders_company_id'), 'ml_orders', ['company_id'], unique=False)
    op.create_index('ix_ml_orders_company_ml_account', 'ml_orders', ['company_id', 'ml_account_id'], unique=False)
    op.create_index(op.f('ix_ml_orders_date_created'), 'ml_orders', ['date_created'], unique=False)
    op.create_index(op.f('ix_ml_orders_id'), 'ml_orders', ['id'], unique=False)
    op.create_index(op.f('ix_ml_orders_last_updated'), 'ml_orders', ['last_updated'], unique=False)
    op.create_index(op.f('ix_ml_orders_ml_account_id'), 'ml_orders', ['ml_account_id'], unique=False)
    op.create_index(op.f('ix_ml_orders_ml_order_id'), 'ml_orders', ['ml_order_id'], unique=True)
    op.create_index(op.f('ix_ml_orders_order_id'), 'ml_orders', ['order_id'], unique=False)
    op.create_index('ix_ml_orders_status', 'ml_orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ml_orders_status', table_name='ml_orders')
    op.drop_index(op.f('ix_ml_orders_order_id'), table_name='ml_orders')
    op.drop_index(op.f('ix_ml_orders_ml_order_id'), table_name='ml_orders')
    op.drop_index(op.f('ix_ml_orders_ml_account_id'), table_name='ml_orders')
    op.drop_index(op.f('ix_ml_orders_last_updated'), table_name='ml_orders')
    op.drop_index(op.f('ix_ml_orders_id'), table_name='ml_orders')
    op.drop_index(op.f('ix_ml_orders_date_created'), table_name='ml_orders')
    op.drop_index('ix_ml_orders_company_ml_account', table_name='ml_orders')
    op.drop_index(op.f('ix_ml_orders_company_id'), table_name='ml_orders')
    op.drop_index('ix_ml_orders_buyer_id', table_name='ml_orders')
    op.drop_table('ml_orders')
    # ### end Alembic commands ###
